name: CI/CD Pipeline

on:
  push:
    branches: [ main ]  # Trigger on pushes to the main branch

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Login to Docker Hub
        run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u arvindpatil1985 --password-stdin

      - name: Build and push Docker image
        run: |
          docker build -t arvindpatil1985/wisecow_app:latest .
          docker push arvindpatil1985/wisecow_app:latest

  # Optional: Deploy to Kubernetes (Challenge Goal)
  deploy-to-kubernetes:  # Uncomment this section and configure for deployment
    runs-on: ubuntu-latest
    needs: build-and-push  # This job depends on the successful completion of build-and-push
    steps:
      - uses: actions/checkout@v3

      - name: Use kubectl (install if missing)
        run: |
          curl -LO https://dl.k8s.io/release/v1.24.0/bin/linux/amd64/kubectl
          chmod +x kubectl
          mkdir ~/bin/
          mv kubectl ~/bin/

      #- name: Configure kubectl (replace with your actual configuration)
        #run: |
          #echo "YOUR_KUBECTL_CONFIG" | base64 -d > ~/.kube/config

      - name: Deploy the application (replace with your deployment manifest)
        run: kubectl apply -f deployment.yaml
