name: CI/CD Pipeline

on:
  push:
    branches: [ main ]  # Trigger on pushes to the main branch

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Login to Docker Hub
        run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u arvindpatil1985 --password-stdin

      - name: Build and push Docker image
        run: |
          docker build -t arvindpatil1985/wisecow_app:latest .
          docker push arvindpatil1985/wisecow_app:latest

  # Optional: Deploy to Kubernetes (Challenge Goal)
  deploy-to-kubernetes:  # Uncomment this section and configure for deployment
    runs-on: ubuntu-latest
    needs: build-and-push  # This job depends on the successful completion of build-and-push
    steps:
      - uses: actions/checkout@v3

      - name: Setup Minikube
        uses: manusa/actions-setup-minikube@v2
        with:
          minikube version: v1.29.2  # Replace with desired version
          kubernetes version: v1.25.5  # Replace with desired version

      - name: Deploy the application (replace with your deployment manifest)
        run: kubectl apply -f deployment.yaml
